_target_: clide.concreteConnector.deployer.packager.sdsp.SDSPPackager

sdspPath: /home/linosbonfi/raid/3.15.0/Toolchain/sdspconv
inputPersistency: false
authClient: FILL_WITH_YOUR
authSecret: FILL_WITH_YOUR
tenantId: 00g4dsbrgt40yTqiI697
packagerVersion: 6.00.00
