_target_: feda.concreteConnector.collector.fileCollector.FileCollector

address: "localhost"
deviceName: "LocalDummy"
imagePath: "/media/raid0/data/xx_settembre_rainy/out_frames_rainy/dev2"
frame_res:
  - 1920
  - 1080