_target_: clide.concreteConnector.collector.fileCollectorRecursive.FileCollectorRecursive

address: "localhost"
deviceName: "LocalDummy"
imagePath: "/home/linosbonfi/raid/cityscape/leftImg8bit"
frame_res:
  - 2048
  - 1024