_target_: clide.concreteConnector.collector.m3u8Collector.M3U8Collector

address: "daxpytip1dec23.ddns.net"
deviceName: "DaxpyXXSettembre"
streamEndpointTemplate: "https://hd-auth.skylinewebcams.com/live.m3u8?a={}"
tokenRegex: ""
bufferSize: 30 
