#florence2:
#  _target_: clide.concreteModel.teacher.florence2.Florence2
#  modelType: FLORENCE_2_BASE
yolo8:
  _target_: clide.concreteModel.teacher.yolo.Yolo
  modelType: YOLOV8X
  hookLayers: ["model.model.4.cv2.conv"]
yolo10:
  _target_: clide.concreteModel.teacher.yolo.Yolo
  modelType: YOLOV10X
  hookLayers: ["model.model.4.cv2.conv"]
yolo11:
  _target_: clide.concreteModel.teacher.yolo.Yolo
  modelType: YOLOV11X
  hookLayers: ["model.model.4.cv2.conv"]