_target_: clide.managers.dataManager.DataManager

dbUri: mongodb://localhost:27017
dbName: testing_db
maxSize: 500 GB
updateRate: 5
unusedRatioThreshold: 0.3
minCollectingTime: 1200 # 20 min
cleanFirst: False