_target_: clide.managers.dataManager.DataManager

dbUri: mongodb://localhost:27017
dbName: testing_db
maxSize: 500 GB
updateRate: 0.5
unusedRatioThreshold: 0.3
minCollectingTime: 900 # 15 min
cleanFirst: True