_target_: clide.trainer.distillationTrainer.UltralyticsTrainer

distillationAlpha: 1
useSoftLabels: False
useFeatureDistillation: False
useImportanceEstimation: False


splitRatio: 
    train: 0.75
    val: 0.25

overrides:
    patience: 5
    epochs: 30