log_level: INFO

defaults:
  - _self_
  - teachers: yolos
  - student: yolo8n
  - datamanager: mongolocal
  - collector: local
  - trainer: ultralyticsConfidence
  - quantizer: mct
  - deployer: dummy
  - logger: wandb